"""Prompt-to-Manim visualization pipeline."""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Optional

from ..providers.visualization import (
    VisualizationRenderer,
    VisualizationRenderRequest,
    create_renderer,
)
from .common import get_reporter
from .events import PipelineReporter
from .highlight import parse_resolution
from .types import (
    PipelineRunResult,
    RenderedVisualClip,
    VisualizationPipelineRequest,
    coerce_request,
)


SCENE_CLASS_NAME = "GeneratedVisualizationScene"
SOURCE_NAME = "generated_visualization.py"
METADATA_NAME = "visualization_metadata.json"
VALID_STYLES = {"clean", "chalkboard", "blueprint", "minimal"}


def _safe_filename(name: str | None, default: str = "visualization.mp4") -> str:
    basename = os.path.basename(name or default)
    stem, ext = os.path.splitext(basename)
    if ext.lower() != ".mp4":
        ext = ".mp4"
    stem = re.sub(r"[^A-Za-z0-9_.-]+", "_", stem).strip("._-")
    return f"{stem or 'visualization'}{ext}"


def _truncate_for_text(value: str, limit: int = 96) -> str:
    text = " ".join(value.split())
    if len(text) <= limit:
        return text
    return text[: limit - 3].rstrip() + "..."


def _idea_lines(prompt: str, audience_level: str) -> list[str]:
    cleaned = " ".join(prompt.split())
    sentences = [s.strip(" .") for s in re.split(r"[.!?;]\s*", cleaned) if s.strip()]
    lines = sentences[:3] or [cleaned]
    if len(lines) < 3:
        lines.append(f"Audience: {audience_level}")
    if len(lines) < 3:
        lines.append("Build intuition from motion, labels, and timing")
    return [_truncate_for_text(line, 80) for line in lines[:3]]


def _style_palette(style: str) -> dict[str, str]:
    palettes = {
        "chalkboard": {
            "background": "#15251B",
            "primary": "YELLOW",
            "secondary": "GREEN",
            "accent": "BLUE",
        },
        "blueprint": {
            "background": "#0E2235",
            "primary": "BLUE_B",
            "secondary": "TEAL",
            "accent": "YELLOW",
        },
        "minimal": {
            "background": "#F8FAFC",
            "primary": "BLUE_D",
            "secondary": "GREY_BROWN",
            "accent": "RED_C",
        },
        "clean": {
            "background": "#111827",
            "primary": "BLUE_B",
            "secondary": "TEAL",
            "accent": "YELLOW",
        },
    }
    return palettes.get(style, palettes["clean"])


def generate_manim_script(request: VisualizationPipelineRequest, width: int, height: int) -> str:
    """Generate ManimGL-compatible source for a concept prompt."""
    style = request.style if request.style in VALID_STYLES else "clean"
    palette = _style_palette(style)
    title = _truncate_for_text(request.prompt, 54)
    ideas = _idea_lines(request.prompt, request.audience_level)
    duration = max(3, int(request.duration_seconds))
    wait = max(0.4, min(2.0, duration / 12))

    return f'''"""Generated by screencastgen visualization pipeline."""

from manimlib import *


PROMPT = {request.prompt!r}


class {SCENE_CLASS_NAME}(Scene):
    def construct(self):
        self.camera.background_color = "{palette["background"]}"

        title = Text({title!r}, font_size=42, weight=BOLD)
        title.to_edge(UP)
        title.set_color({palette["primary"]})

        subtitle = Text(
            {f"{request.audience_level.title()} level - {style} style"!r},
            font_size=24,
        )
        subtitle.next_to(title, DOWN, buff=0.2)
        subtitle.set_color(GREY_B)

        axes = Axes(
            x_range=(-4, 4, 1),
            y_range=(-2, 2, 1),
            width=8.8,
            height=3.6,
        )
        axes.shift(DOWN * 0.55)
        axes.set_color(GREY_B)

        curve = axes.get_graph(lambda x: 0.45 * np.sin(1.4 * x) + 0.2 * x, color={palette["secondary"]})
        moving_dot = Dot(color={palette["accent"]})
        moving_dot.move_to(curve.get_start())
        trace = TracedPath(moving_dot.get_center, stroke_color={palette["accent"]}, stroke_width=4)

        idea_box = VGroup(
            Text({ideas[0]!r}, font_size=25),
            Text({ideas[1]!r}, font_size=25),
            Text({ideas[2]!r}, font_size=25),
        )
        idea_box.arrange(DOWN, aligned_edge=LEFT, buff=0.25)
        idea_box.to_edge(DOWN, buff=0.55)
        idea_box.set_color(WHITE)

        labels = VGroup(
            Text("input", font_size=22).next_to(axes.x_axis.get_end(), RIGHT),
            Text("output", font_size=22).next_to(axes.y_axis.get_end(), UP),
        )
        labels.set_color(GREY_B)

        self.play(FadeIn(title, shift=DOWN * 0.2), FadeIn(subtitle), run_time=1.2)
        self.play(ShowCreation(axes), FadeIn(labels), run_time=1.3)
        self.play(ShowCreation(curve), run_time=1.8)
        self.add(trace)
        self.play(MoveAlongPath(moving_dot, curve), run_time=max(2.0, {duration} * 0.28), rate_func=smooth)
        self.play(LaggedStartMap(FadeIn, idea_box, shift=UP * 0.15, lag_ratio=0.18), run_time=1.5)
        self.wait({wait})
        self.play(
            curve.animate.set_stroke(width=8),
            title.animate.set_color({palette["accent"]}),
            run_time=0.8,
        )
        self.wait({wait})
'''


def _probe_duration(path: str) -> Optional[float]:
    try:
        from moviepy import VideoFileClip

        with VideoFileClip(path) as clip:
            return float(clip.duration)
    except Exception:
        return None


def _write_metadata(path: str, data: dict) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def run_visualization_pipeline(
    request,
    *,
    reporter: Optional[PipelineReporter] = None,
    renderer: Optional[VisualizationRenderer] = None,
) -> PipelineRunResult:
    """Generate a Manim scene and render it to a standalone MP4."""
    reporter = get_reporter(reporter)
    request = coerce_request(VisualizationPipelineRequest, request)
    prompt = request.prompt.strip()
    if not prompt:
        return PipelineRunResult(exit_code=1, error_message="Visualization prompt is required")

    try:
        width, height = parse_resolution(request.resolution)
    except Exception as exc:
        return PipelineRunResult(exit_code=1, error_message=str(exc))

    if width < 320 or height < 240 or width > 3840 or height > 2160:
        return PipelineRunResult(exit_code=1, error_message="Resolution must be between 320x240 and 3840x2160")
    if request.fps < 1 or request.fps > 60:
        return PipelineRunResult(exit_code=1, error_message="FPS must be between 1 and 60")
    if request.provider not in {"manimgl", "manimce"}:
        return PipelineRunResult(exit_code=1, error_message=f"Unknown visualization renderer: {request.provider}")

    output_name = _safe_filename(request.output)
    os.makedirs(request.output_dir, exist_ok=True)
    source_path = os.path.join(request.output_dir, SOURCE_NAME)

    reporter.phase_start("generating", "\n=== GENERATING MANIM SCENE ===")
    code = generate_manim_script(request, width, height)
    with open(source_path, "w", encoding="utf-8") as f:
        f.write(code)
    reporter.line(f"  Source: {source_path}")

    try:
        active_renderer = renderer or create_renderer(request.provider)
    except Exception as exc:
        return PipelineRunResult(exit_code=1, output_name=output_name, error_message=str(exc))

    render_request = VisualizationRenderRequest(
        scene_file=source_path,
        scene_class=SCENE_CLASS_NAME,
        output_dir=request.output_dir,
        output_name=output_name,
        width=width,
        height=height,
        fps=request.fps,
        timeout_seconds=request.timeout_seconds,
        max_output_bytes=request.max_output_bytes,
    )

    reporter.phase_start("rendering", "\n=== RENDERING MANIM SCENE ===")
    render_result = active_renderer.render(render_request)

    metadata = {
        "prompt": prompt,
        "provider": request.provider,
        "scene_class": SCENE_CLASS_NAME,
        "source_name": SOURCE_NAME,
        "source_path": source_path,
        "generated_code": code,
        "output_name": output_name,
        "render_command": render_result.command,
        "returncode": render_result.returncode,
        "stdout_excerpt": render_result.stdout,
        "stderr_excerpt": render_result.stderr,
        "renderer_metadata": render_result.metadata,
    }

    if not render_result.success or not render_result.output_path:
        error = render_result.error_message or "Visualization render failed"
        if render_result.stderr:
            error = f"{error}\n\n{render_result.stderr}"
        _write_metadata(os.path.join(request.output_dir, METADATA_NAME), metadata)
        return PipelineRunResult(
            exit_code=1,
            output_name=output_name,
            error_message=error,
            metadata=metadata,
        )

    duration = _probe_duration(render_result.output_path)
    clip = RenderedVisualClip(
        path=render_result.output_path,
        duration=duration,
        fps=request.fps,
        width=width,
        height=height,
        source_prompt=prompt,
        source_code=code,
    )
    metadata["clip"] = {
        "path": clip.path,
        "duration": clip.duration,
        "fps": clip.fps,
        "width": clip.width,
        "height": clip.height,
        "source_prompt": clip.source_prompt,
        "source_code": clip.source_code,
    }
    _write_metadata(os.path.join(request.output_dir, METADATA_NAME), metadata)
    reporter.line(f"\nDone: {render_result.output_path}")
    return PipelineRunResult(
        exit_code=0,
        output_name=output_name,
        output_path=render_result.output_path,
        metadata=metadata,
    )
